spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO_URL}
          default-label: main
          search-paths: '*/**'
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          clone-on-start: true
server:
  port: 8888
